extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
language: en
theme: 
    name: lantana
    locale: en
visible_search: true
plugins:
    - search:
        lang : 'en'
        min_search_length: 2
    - macros
    - awesome-pages
    - git-authors
markdown_extensions:
    - attr_list
    - pymdownx.highlight:
       anchor_linenums: true
    - admonition
    - pymdownx.arithmatex:
       generic : true
    - md_in_html
    - pymdownx.details
    - pymdownx.superfences:
        custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format
    - pymdownx.snippets
    - pymdownx.critic
    - pymdownx.caret
    - pymdownx.keys
    - pymdownx.mark
    - pymdownx.tilde
    - pymdownx.emoji:
        emoji_index: !!python/name:material.extensions.emoji.twemoji
        emoji_generator: !!python/name:material.extensions.emoji.to_svg
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.magiclink
    - pymdownx.striphtml
site_name: Caten Documentation

nav:
  - Home: index.md
  - Quickstart: quickstart.md
  - Development: development.md
  - API Reference:
    - caten/air: packages/caten.air.md
    - caten/aasm: packages/caten.aasm.md
    - caten/codegen: packages/caten.codegen.md
    - caten/polyhedral: packages/caten.polyhedral.md
    - caten/apis:
      - Overview: packages/caten.apis.md
      - Tensor: packages/caten.apis.tensor.md
      - Func: packages/caten.apis.differentiable_ops.md
      - Module: packages/caten.apis.module.md
      - Model: packages/caten.apis.models.md
      - AOT: packages/caten.apis.aot.md
      - Initializers: packages/caten.apis.initializers.md
      - ShapeTracker: packages/caten.apis.shapetracker.md
    - caten/avm: packages/caten.avm.md
    - caten/nn: packages/caten.nn.md
