(in-package :caten/aasm)

(defun $affine (writes reads)
  (declare (type list writes reads))
  (emit (make-node :Schedule :Affine writes reads)))

(defun $nonaffine (writes reads &key (items))
  (declare (type list writes reads))
  (emit (make-node :Schedule :NonAffine writes reads :items items)))

(defmethod print-node ((node Node) (id (eql :Affine)))
  (with-output-to-string (out)
    (format out "~a = Affine(~a){~%" (render-list (node-writes node)) (render-list (node-reads node)))
    (format out "    TODO: [Program]~%")
    (format out "}")))

(defmethod print-node ((node Node) (id (eql :NonAffine)))
  (with-output-to-string (out)
    (format out "~a = NonAffine(~a){~%" (render-list (node-writes node)) (render-list (node-reads node)))
    (dolist (item (getattr node :items))
      (let ((prefix (if (find (car (node-writes item)) (node-writes node))
                        (format nil "  return ")
                        (format nil "  ~(~a~) = " (render-list (node-writes item))))))
        (format out "~a~(~a~)(~(~a~));~%" prefix (node-type item) (render-list (node-reads item)))))
    (format out "}")))
