name: Publish docs via Github Pages
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up SBCL via Roswell.
        run: |
          curl -L https://raw.githubusercontent.com/roswell/roswell/master/scripts/install-for-ci.sh | sh
          ros install sbcl-bin/2.4.0
          ros use sbcl-bin/2.4.0
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Installing ISL
        run: sudo apt-get install -y libisl-dev
      - name: Installing requirements
        run: make install_docs
      - name: Building documentations
        run: mkdir -p docs/packages && make build_docs && echo -e "markdown-katex\nlantana" > docs/requirements.txt
      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CUSTOM_DOMAIN: optionaldomain.com
          CONFIG_FILE: mkdocs.yml
          EXTRA_PACKAGES: build-base
          REQUIREMENTS: ./docs/requirements.txt