name: CI
on:
  push:
    branches:
      - main
  pull_request:
      branches:
        - main

jobs:
  UnitTest:
    name: Unittests on (${{ matrix.lisp }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        lisp: [sbcl-bin, ccl-bin, ecl]
        os: [ubuntu-latest]
        target:
        - normal
    steps:
      - uses: actions/checkout@v1
      - name: Set up ${{ matrix.lisp }} via Roswell.
        env:
          LISP: ${{ matrix.lisp }}
        run: |
          curl -L https://raw.githubusercontent.com/roswell/roswell/master/scripts/install-for-ci.sh | sh
      - name: Installing dependencies (libisl-dev, and rove)
        run: |
          sudo apt-get install -y libisl-dev
          ros -e '(ql-dist:install-dist "http://dist.shirakumo.org/shirakumo.txt")' -q # https://github.com/Shinmera/dissect/issues/18
          ros install rove
      - name: Update $PATH
        run: |
          echo $PATH
          export PATH=/home/runner/.roswell/bin:$PATH
          echo "PATH=$HOME/bin:$PATH" >> $GITHUB_ENV
      - name: Check $PATH
        run: echo $PATH
      - name: Run unittest with VM+Lisp
        run: |
          ros config set dynamic-space-size 4gb
          ros -e '(ql:register-local-projects)' -q
          rove caten.asd
