name: CI
on:
  push:
    branches:
      - main
  pull_request:
      branches:
        - main
        - develop

jobs:
  UnitTest:
    name: (${{ matrix.backend }}) Unittests on (${{ matrix.lisp }})
    runs-on: ${{ matrix.os }}
    timeout-minutes: 25
    strategy:
      matrix:
        lisp: [sbcl-bin, ccl-bin/1.12.2]
        backend: [lisp, clang]
        os: [ubuntu-latest]
        target:
        - normal
    steps:
      - uses: actions/checkout@v1
      - name: Set up ${{ matrix.lisp }} via Roswell.
        env:
          LISP: sbcl-bin
        run: |
          curl -L https://raw.githubusercontent.com/roswell/roswell/master/scripts/install-for-ci.sh | sh
          ros install ${{ matrix.lisp }}
          ros use ${{ matrix.lisp }}
          ros install rove qlot
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Installing libisl-dev
        run: |
          sudo apt-get install -y libisl-dev
      - name: pkg-config isl --modversion
        run: |
          pkg-config isl --modversion
      - name: Update $PATH
        run: |
          echo $PATH
          export PATH=/home/runner/.roswell/bin:$PATH
          echo "PATH=$HOME/bin:$PATH" >> $GITHUB_ENV
      - name: Installing Extra Dependency for testing
        run: make install_extra
      - name: Check $PATH
        run: echo $PATH
      - name: (Lisp) rove caten.asd
        if: ${{ matrix.backend == 'lisp' }}
        run: |
          ros config set dynamic-space-size 8gb
          ros -e '(ql:register-local-projects)' -q
          CI=1 JIT=0 AVM=LISP rove caten.asd
      - name: (Clang) rove caten.asd
        if: ${{ matrix.backend == 'clang' && matrix.lisp != 'ccl-bin/1.12.2' }}
        run: |
          ulimit -n 8192
          ros config set dynamic-space-size 8gb
          ros -e '(ql:register-local-projects)' -q
          CI=1 JIT=1 JIT_BACKEND=CLANG AVM=LISP rove caten.asd
  Documentation:
    name: Test building documentations
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v1
      - name: Set up SBCL via Roswell.
        run: |
          curl -L https://raw.githubusercontent.com/roswell/roswell/master/scripts/install-for-ci.sh | sh
          ros install sbcl-bin
          ros use sbcl-bin
          ros install qlot
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Update $PATH
        run: |
          echo $PATH
          export PATH=/home/runner/.roswell/bin:$PATH
          echo "PATH=$HOME/bin:$PATH" >> $GITHUB_ENV
      - name: Installing ISL
        run: sudo apt-get install -y libisl-dev
      - name: Installing requirements
        run: |
          qlot install
          qlot exec make install_docs
      - name: Building documentations
        run: CI=1 mkdir -p docs/packages && make build_docs
  Compiler_Benchmark:
    name: Benchmark
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v1
      - name: Set up SBCL via Roswell.
        run: |
          curl -L https://raw.githubusercontent.com/roswell/roswell/master/scripts/install-for-ci.sh | sh
          ros install sbcl-bin
          ros use sbcl-bin
          ros install qlot
          qlot install
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Update $PATH
        run: |
          echo $PATH
          export PATH=/home/runner/.roswell/bin:$PATH
          echo "PATH=$HOME/bin:$PATH" >> $GITHUB_ENV
      - name: Installing Dependencies
        run: sudo apt-get install -y libisl-dev gnuplot
      - name: Transformer Simplifiers (N<=12, JIT=0, AUTO_SCHEDULER=0)
        run: PROFILE_SIMPLIFIER=1 qlot exec ./roswell/caten.ros benchmark transformer_compile_time 36 0 transformer_simplifier_plot.png
      - name: Transformer Schedulers (N<=12, JIT=1, AUTO_SCHEDULER=0)
        run: PARALLEL=4 PROFILE_SIMPLIFIER=1 JIT_DEBUG=2 AUTO_SCHEDULER=0 qlot exec ./roswell/caten.ros benchmark transformer_compile_time 12 1 transformer_simplifier_no_auto_sched_plot.png
#      - name: Transformer Schedulers (N<=12, JIT=1, AUTO_SCHEDULER=1)
#        run: PROFILE_SIMPLIFIER=1 JIT_DEBUG=2 AUTO_SCHEDULER=1 qlot exec ./roswell/caten.ros benchmark transformer_compile_time 24 1 transformer_simplifier_auto_scheduler_plot.png
