name: CI
on:
  push:
    branches:
      - main
  pull_request:
      branches:
        - main

jobs:
  UnitTest:
    name: (${{ matrix.backend }}) Unittests on (${{ matrix.lisp }})
    runs-on: ${{ matrix.os }}
    timeout-minutes: 20
    strategy:
      matrix:
        lisp: [sbcl-bin/2.4.0, ccl-bin/1.12.2] # Caten should work on the latest sbcl; but (ql:quickload :dissect) which rove depends on, fails with > sbcl-bin/2.4.2
        backend: [lisp, clang]
        os: [ubuntu-latest]
        target:
        - normal
    steps:
      - uses: actions/checkout@v1
      - name: Set up ${{ matrix.lisp }} via Roswell.
        env:
          LISP: sbcl-bin/2.4.0 # Install rove with the older version of SBCL to pass (ql:quickload :dissect)
        run: |
          curl -L https://raw.githubusercontent.com/roswell/roswell/master/scripts/install-for-ci.sh | sh
          ros install ${{ matrix.lisp }}
          ros use ${{ matrix.lisp }}
          ros install rove
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Installing libisl-dev
        run: |
          sudo apt-get install -y libisl-dev
      - name: pkg-config isl --modversion
        run: |
          pkg-config isl --modversion
      - name: Update $PATH
        run: |
          echo $PATH
          export PATH=/home/runner/.roswell/bin:$PATH
          echo "PATH=$HOME/bin:$PATH" >> $GITHUB_ENV
      - name: Installing Extra Dependency for testing
        run: make install_extra
      - name: Check $PATH
        run: echo $PATH
      - name: (Lisp) rove caten.asd
        if: ${{ matrix.backend == 'lisp' }}
        run: |
          ros config set dynamic-space-size 8gb
          ros -e '(ql:register-local-projects)' -q
          CI=1 JIT=0 AVM=LISP rove caten.asd
      - name: (Clang) rove caten.asd
        if: ${{ matrix.backend == 'clang' && matrix.lisp != 'ccl-bin/1.12.2' }}
        run: |
          ulimit -n 8192
          ros config set dynamic-space-size 8gb
          ros -e '(ql:register-local-projects)' -q
          CI=1 JIT=1 JIT_BACKEND=CLANG AVM=LISP rove caten.asd
  Documentation:
    name: Test building documentations
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v1
      - name: Set up SBCL via Roswell.
        run: |
          curl -L https://raw.githubusercontent.com/roswell/roswell/master/scripts/install-for-ci.sh | sh
          ros install sbcl-bin/2.4.0
          ros use sbcl-bin/2.4.0
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Installing ISL
        run: sudo apt-get install -y libisl-dev
      - name: Installing requirements
        run: make install_docs
      - name: Building documentations
        run: CI=1 mkdir -p docs/packages && make build_docs